services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: